# frozen_string_literal: true

Conjugations = { "Objects" => { "1s.OBJ" => "-wa", "3s.IDO" => "-ri" },
                 "Temporal Aspects" =>
                   { "Durative/Infinitive" => "-na",
                     "Ingressive" => "-gri",
                     "Past Participle" => "-shka",
                     "Same Subject Gerund" => "-shpa",
                     "Different Subject Subordinator" => "-kpi",
                     "Habitual/Agent" => "-k",
                     "Nominal/Verbal infinitive" => "-i" },
                 "Auxiliaries" => { "Euphonic" => "-n" },
                 "Atemporal Aspects" => { "Reflexive" => "-ri" },
                 "Casuals" =>
                   { "Comparative" => "-shina",
                     "Terminative" => "-kama",
                     "Allative/Dative" => "-man",
                     "Ablative/Causal" => "-manta",
                     "Accusative/Adverbial/Prolative" => "-ta",
                     "Benefactive/Genitive" => "-pak",
                     "Locative" => "-pi",
                     "Instrumental/Comitative" => "-wan" },
                 "Conjunctives" =>
                   { "Inclusive/Comitative" => "-ndi(n)",
                     "Conjunctive" => "-pura",
                     "Additive" => "-pish/-pash",
                     "Contrastive" => "-tak" },
                 "Derived Qualitatives" => { "Superlative" => "-pacha" },
                 "Derived Quantities" =>
                   { "Augmentative" => "-sapa",
                     "Exceditive?/Pejorative/Exaggeration" => "-siki",
                     "Additive" => "-pish/-pash" },
                 "Derived Radicals" =>
                   { "Cislocative" => "-mu",
                     "Reflexive/Progressive" => "-ku",
                     "Reflexive" => "-ri",
                     "Causative" => "-chi",
                     "Reciprocal" => "-naku",
                     "Conjunctive" => "-pura",
                     "Ingressive" => "-gri",
                     "Terminative Verb Marker" => "-ngakaman",
                     "Propositive/Benefactive" => "-ngapa(k)" },
                 "Evidential Clitics" => { "Topic" => "-ka", "Focus/Validator" => "-mi/-ma" },
                 "Specific Clitics" => { "Limitative" => "-lla", "Continuative" => "-ra(k)" },
                 "Modals" => { "Conditional" => "-man", "Future/Obligative" => "-na" },
                 "Operators" => { "Interrogative" => "-chu", "Negation" => "-chu" },
                 "Personal Verb Markers" =>
                   { "1s.PRES" => "-ni",
                     "2s.PRES" => "-ngi",
                     "3s.PRES" => "-n",
                     "1p.PRES" => "-nchi(k)",
                     "2p.PRES" => "-ngichi(k)",
                     "3p.PRES" => "-n(kuna)" },
                 "Personal Temporal Verb Markers" =>
                   { "1p.FUT" => "-shun",
                     "2s.FUT" => "-ngi",
                     "2p.FUT" => "-ngichi(k)",
                     "3s.FUT" => "-nga",
                     "3p.FUT" => "-n(kuna)",
                     "2s.imperative" => "-i",
                     "2p.imperative" => "-ichi(k)",
                     "Exclusive Exhortative" => "-shun",
                     "Inclusive Exhortative" => "-shunchik" },
                 "Pluralizer" => { "Plural" => "-kuna" },
                 "Possessives" =>
                   { "Alienable Possessive" => "-pa(k)", "Inalienable Possessive" => "-yuk" },
                 "Pragmatic Evidentials" =>
                   { "Dubitative" => "-chari",
                     "Supposition" => "-shi",
                     "Exceditive Affirmation" => "-karin",
                     "Confirmative Affirmation" => "-mari" },
                 "Temporal" =>
                   { "Habitual Preterite" => "-k",
                     "Simple Preterite" => "-rka",
                     "Perfective/Past Participle" => "-shka" } }
